services:
  - type: web
    name: qr-attendance
    env: python
    plan: free
    buildCommand: |
      apt-get update && \
      apt-get install -y libzbar0 && \
      pip install -r requirements.txt
    startCommand: streamlit run app.py
